version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  test:e2e:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: yarn
          pkg-manager: yarn
      - run:
          command: yarn run test:e2e
          name: Run YARN tests e2e

workflows:
  test_my_app:
    jobs:
      - test
      - test:e2e
